apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: 'app'
    server: https://kubernetes.default.svc
  source:
    path: helm/backend
    repoURL: https://github.com/monukoni/kubernetes
    targetRevision: HEAD
    helm:
      valueFiles:
        - backend-values.yml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
