apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: 'consul'
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://helm.releases.hashicorp.com'
      chart: consul
      targetRevision: 1.9.2
      helm:
        valueFiles:
          - $values/helm-values/consul-values.yml
    - repoURL: 'https://github.com/monukoni/kubernetes'
      targetRevision: add-argocd
      ref: values
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
