apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: 'app'
    server: https://kubernetes.default.svc
  source:
    path: helm/frontend
    repoURL: https://github.com/monukoni/kubernetes
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
